const NoteApi = {
    userSignUp: '/user/userSignUp',
    userLogin: '/user/login',
    userReset: '/user/reset',
    resetUserPassword: '/user/reset-password',
    addNotes: '/notes/addNotes',
    getNotes: '/notes/getNotesList',
    SearchUserDetails: '/user/searchUserList',
    saveNoteLabels: '/noteLabels',
    pinUnpinNotes: '/notes/pinUnpinNotes',
    ArchiveNote: '/notes/archiveNotes',
    NoteColor: '/notes/changesColorNotes',
    updateNotes: '/notes/updateNotes',
    getLabelList: '/noteLabels/getNoteLabelList',
    updateNoteLabel: '/updateNoteLabel',
    deleteNoteLabel: '/deleteNoteLabel',
    TrashNotes: '/notes/trashNotes',
    PermanentDeleteNotes: '/notes/deleteForeverNotes',
    notes: '/notes/',
    addNoteLabels: '/noteLabels',
    addCollaborator: '/AddcollaboratorsNotes',
    addReminder: '/notes/addUpdateReminderNotes',
    checkList: '/checklist/',
    update: '/update'
  };
  export default NoteApi;